rootProject.name = 'ecommerce-platform'

include 'services:common'
include 'services:service-discovery'
include 'services:api-gateway'
include 'services:identity-access-service'
include 'services:catalog-service'
include 'services:pricing-service'
include 'services:cart-service'
include 'services:inventory-service'
include 'services:order-service'
include 'services:payment-service'
include 'services:fulfillment-service'
include 'services:notification-service'
include 'services:audit-compliance-service'
include 'services:business-configuration-service'
include 'services:exception-management-service'
