import { Category, Product, CustomerAddress, Order } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-fashion',
    name: 'Thời trang & May mặc',
    code: 'FASHION',
    displayOrder: 1,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
    subcategories: [
      { id: 'cat-fashion-men', name: 'Thời trang Nam', code: 'MEN_FASHION', parentId: 'cat-fashion', displayOrder: 1, isActive: true },
      { id: 'cat-fashion-women', name: 'Thời trang Nữ', code: 'WOMEN_FASHION', parentId: 'cat-fashion', displayOrder: 2, isActive: true },
    ],
  },
  {
    id: 'cat-tech',
    name: 'Thiết bị & Công nghệ',
    code: 'TECH',
    displayOrder: 2,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    subcategories: [
      { id: 'cat-audio', name: 'Tai nghe & Âm thanh', code: 'AUDIO', parentId: 'cat-tech', displayOrder: 1, isActive: true },
      { id: 'cat-wearables', name: 'Đồng hồ thông minh', code: 'WEARABLES', parentId: 'cat-tech', displayOrder: 2, isActive: true },
    ],
  },
  {
    id: 'cat-accessories',
    name: 'Phụ kiện cao cấp',
    code: 'ACCESSORIES',
    displayOrder: 3,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    subcategories: [
      { id: 'cat-bags', name: 'Balo & Túi xách', code: 'BAGS', parentId: 'cat-accessories', displayOrder: 1, isActive: true },
      { id: 'cat-eyewear', name: 'Kính mắt thời trang', code: 'EYEWEAR', parentId: 'cat-accessories', displayOrder: 2, isActive: true },
    ],
  },
  {
    id: 'cat-lifestyle',
    name: 'Không gian sống & Decor',
    code: 'LIFESTYLE',
    displayOrder: 4,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80',
    subcategories: [
      { id: 'cat-desk', name: 'Bàn làm việc & Setup', code: 'DESK_SETUP', parentId: 'cat-lifestyle', displayOrder: 1, isActive: true },
    ],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'Áo Hoodie Minimalist Heavyweight Oversized',
    slug: 'ao-hoodie-minimalist-heavyweight-oversized',
    description: 'Chất liệu nỉ cotton 100% định lượng 450gsm siêu dày dặn, giữ ấm tối ưu với form dáng rủ hiện đại chuẩn phong cách Scandinavian minimalism. Bo thun dệt kim chống dão, đường may tỉ mỉ đôi viền.',
    category: MOCK_CATEGORIES[0],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 4.9,
    reviewCount: 128,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    skus: [
      {
        id: 'sku-001-blk-m',
        skuCode: 'HD-BLK-M',
        price: 850000,
        salePrice: 680000, // BR-013 Promo
        isActive: true,
        attributes: { Color: 'Đen (Obsidian)', Size: 'M' },
        inventory: { quantityOnHand: 25, quantityReserved: 5, quantityAvailable: 20 },
      },
      {
        id: 'sku-001-blk-l',
        skuCode: 'HD-BLK-L',
        price: 850000,
        salePrice: 680000,
        isActive: true,
        attributes: { Color: 'Đen (Obsidian)', Size: 'L' },
        inventory: { quantityOnHand: 3, quantityReserved: 1, quantityAvailable: 2 }, // Low stock urgency!
      },
      {
        id: 'sku-001-gry-m',
        skuCode: 'HD-GRY-M',
        price: 850000,
        isActive: true,
        attributes: { Color: 'Xám Khói (Heather)', Size: 'M' },
        inventory: { quantityOnHand: 15, quantityReserved: 0, quantityAvailable: 15 },
      },
      {
        id: 'sku-001-gry-l',
        skuCode: 'HD-GRY-L',
        price: 850000,
        isActive: true,
        attributes: { Color: 'Xám Khói (Heather)', Size: 'L' },
        inventory: { quantityOnHand: 0, quantityReserved: 0, quantityAvailable: 0 }, // Out of stock
      },
    ],
  },
  {
    id: 'prod-002',
    name: 'Tai nghe Không dây Hi-Res Spatial Audio Studio X',
    slug: 'tai-nghe-khong-day-hi-res-spatial-audio-studio-x',
    description: 'Trải nghiệm âm thanh vòm không gian chuẩn phòng thu với màng loa Bio-Cellulose 40mm, công nghệ Chống ồn chủ động Hybrid ANC thích ứng môi trường. Thời lượng pin 45 giờ liên tục, đệm tai da cừu êm ái.',
    category: MOCK_CATEGORIES[1],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 4.8,
    reviewCount: 96,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    skus: [
      {
        id: 'sku-002-slv',
        skuCode: 'HP-SLV-PRO',
        price: 3890000,
        salePrice: 3290000, // BR-013
        isActive: true,
        attributes: { Color: 'Bạc Titan (Titanium Silver)', Edition: 'Standard' },
        inventory: { quantityOnHand: 8, quantityReserved: 3, quantityAvailable: 5 },
      },
      {
        id: 'sku-002-blk',
        skuCode: 'HP-BLK-PRO',
        price: 3890000,
        isActive: true,
        attributes: { Color: 'Đen Mờ (Matte Black)', Edition: 'Standard' },
        inventory: { quantityOnHand: 18, quantityReserved: 4, quantityAvailable: 14 },
      },
    ],
  },
  {
    id: 'prod-003',
    name: 'Balo Công thái học Urban Commuter Chống Nước',
    slug: 'balo-cong-thai-hoc-urban-commuter-chong-nuoc',
    description: 'Chất liệu Cordura 1000D kháng nước vượt trội đạt chuẩn IPX4. Ngăn chống sốc bảo vệ laptop 16-inch lót lông nhung cao cấp, khóa kéo YKK AquaGuard chính hãng, đệm lưng thoáng khí giảm áp lực cột sống.',
    category: MOCK_CATEGORIES[2],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 4.7,
    reviewCount: 64,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    skus: [
      {
        id: 'sku-003-blk',
        skuCode: 'BP-URB-BLK',
        price: 1450000,
        salePrice: 1250000,
        isActive: true,
        attributes: { Color: 'Đen Carbon', Capacity: '22L' },
        inventory: { quantityOnHand: 12, quantityReserved: 2, quantityAvailable: 10 },
      },
      {
        id: 'sku-003-olv',
        skuCode: 'BP-URB-OLV',
        price: 1450000,
        isActive: true,
        attributes: { Color: 'Xanh Rêu (Olive Green)', Capacity: '22L' },
        inventory: { quantityOnHand: 4, quantityReserved: 1, quantityAvailable: 3 }, // Urgency
      },
    ],
  },
  {
    id: 'prod-004',
    name: 'Đồng hồ Cơ Tự động Chronograph Sapphire Edition',
    slug: 'dong-ho-co-tu-dong-chronograph-sapphire-edition',
    description: 'Bộ máy cơ tự động Caliber 8215 trữ cót 42 giờ, mặt kính Sapphire nguyên khối chống trầy xước phủ AR chống lóa. Vỏ thép không gỉ 316L đánh bóng mờ cao cấp, dây da bò Ý thuộc thảo mộc.',
    category: MOCK_CATEGORIES[2],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 5.0,
    reviewCount: 42,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    skus: [
      {
        id: 'sku-004-brw',
        skuCode: 'WAT-AUT-BRW',
        price: 5200000,
        salePrice: 4680000,
        isActive: true,
        attributes: { Dial: 'Trắng Bạc', Strap: 'Da Nâu' },
        inventory: { quantityOnHand: 5, quantityReserved: 1, quantityAvailable: 4 },
      },
      {
        id: 'sku-004-blk',
        skuCode: 'WAT-AUT-BLK',
        price: 5200000,
        isActive: true,
        attributes: { Dial: 'Đen Men', Strap: 'Da Đen' },
        inventory: { quantityOnHand: 2, quantityReserved: 0, quantityAvailable: 2 }, // Low stock!
      },
    ],
  },
  {
    id: 'prod-005',
    name: 'Đèn Bàn Công nghệ LED Smart Spectrum Pro',
    slug: 'den-ban-cong-nghe-led-smart-spectrum-pro',
    description: 'Chỉ số hoàn màu CRI Ra≥98 bảo vệ thị lực tuyệt đối. Khung nhôm nguyên khối gia công CNC sắc nét, cảm ứng trượt điều chỉnh độ sáng vô cấp và nhiệt độ màu từ 2700K đến 6500K.',
    category: MOCK_CATEGORIES[3],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 4.6,
    reviewCount: 38,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    skus: [
      {
        id: 'sku-005-slv',
        skuCode: 'LMP-SPC-SLV',
        price: 1850000,
        salePrice: 1590000,
        isActive: true,
        attributes: { Finish: 'Nhôm Bạc Xước (Silver)' },
        inventory: { quantityOnHand: 20, quantityReserved: 2, quantityAvailable: 18 },
      },
      {
        id: 'sku-005-dgy',
        skuCode: 'LMP-SPC-DGY',
        price: 1850000,
        isActive: true,
        attributes: { Finish: 'Xám Không Gian (Space Gray)' },
        inventory: { quantityOnHand: 10, quantityReserved: 1, quantityAvailable: 9 },
      },
    ],
  },
  {
    id: 'prod-006',
    name: 'Áo Thun Pima Cotton Supima Kháng Khuẩn Tự Nhiên',
    slug: 'ao-thun-pima-cotton-supima-khang-khuan-tu-nhien',
    description: 'Dệt từ 100% sợi Supima cotton sợi siêu dài thượng hạng từ Tây Nam nước Mỹ. Độ bền gấp đôi cotton thông thường, bề mặt láng mượt bóng nhẹ tự nhiên và giữ form cổ hoàn hảo sau 100 lần giặt.',
    category: MOCK_CATEGORIES[0],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 4.9,
    reviewCount: 215,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    skus: [
      {
        id: 'sku-006-wht-m',
        skuCode: 'TSH-SUP-WHT-M',
        price: 490000,
        salePrice: 390000,
        isActive: true,
        attributes: { Color: 'Trắng Sữa (Off-White)', Size: 'M' },
        inventory: { quantityOnHand: 50, quantityReserved: 5, quantityAvailable: 45 },
      },
      {
        id: 'sku-006-wht-l',
        skuCode: 'TSH-SUP-WHT-L',
        price: 490000,
        salePrice: 390000,
        isActive: true,
        attributes: { Color: 'Trắng Sữa (Off-White)', Size: 'L' },
        inventory: { quantityOnHand: 30, quantityReserved: 2, quantityAvailable: 28 },
      },
      {
        id: 'sku-006-blk-m',
        skuCode: 'TSH-SUP-BLK-M',
        price: 490000,
        isActive: true,
        attributes: { Color: 'Đen Nhám (Jet Black)', Size: 'M' },
        inventory: { quantityOnHand: 15, quantityReserved: 2, quantityAvailable: 13 },
      },
      {
        id: 'sku-006-nvy-m',
        skuCode: 'TSH-SUP-NVY-M',
        price: 490000,
        isActive: true,
        attributes: { Color: 'Xanh Navy Đậm', Size: 'M' },
        inventory: { quantityOnHand: 3, quantityReserved: 1, quantityAvailable: 2 }, // Low stock!
      },
    ],
  },
  {
    id: 'prod-007',
    name: 'Bình Giữ Nhiệt Chân Không Thép Titan Minimalist 750ml',
    slug: 'binh-giu-nhiet-chan-khong-thep-titan-minimalist-750ml',
    description: 'Công nghệ chân không 3 lớp giữ nóng 18h và giữ lạnh 36h. Ruột bình tráng gốm Ceramic cao cấp không để lại mùi vị, nắp khóa từ tính một chạm tiện lợi, dây quai silicon chống trượt.',
    category: MOCK_CATEGORIES[3],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 4.8,
    reviewCount: 89,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    skus: [
      {
        id: 'sku-007-blk',
        skuCode: 'BTL-TTN-BLK',
        price: 690000,
        salePrice: 550000,
        isActive: true,
        attributes: { Color: 'Đen Mờ (Matte Black)' },
        inventory: { quantityOnHand: 16, quantityReserved: 2, quantityAvailable: 14 },
      },
      {
        id: 'sku-007-wht',
        skuCode: 'BTL-TTN-WHT',
        price: 690000,
        isActive: true,
        attributes: { Color: 'Trắng Sứ (Ceramic White)' },
        inventory: { quantityOnHand: 10, quantityReserved: 0, quantityAvailable: 10 },
      },
    ],
  },
  {
    id: 'prod-008',
    name: 'Kính Râm Phân Cực UV400 Khung Titanium Siêu Nhẹ',
    slug: 'kinh-ram-phan-cuc-uv400-khung-titanium-sieu-nhe',
    description: 'Trọng lượng siêu nhẹ chỉ 14.5g nhờ gọng hợp kim Titanium hàng không. Tròng kính Polarized 9 lớp lọc 100% tia tử ngoại UV400, chống chói lóa khi lái xe hoặc đi dưới nắng gắt.',
    category: MOCK_CATEGORIES[2],
    status: 'ACTIVE',
    mediaUrls: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=1000&q=85',
    ],
    rating: 4.7,
    reviewCount: 54,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    skus: [
      {
        id: 'sku-008-gun',
        skuCode: 'SGL-TTN-GUN',
        price: 1890000,
        salePrice: 1590000,
        isActive: true,
        attributes: { Frame: 'Xám Nòng Súng (Gunmetal)', Lens: 'Đen Phân Cực' },
        inventory: { quantityOnHand: 14, quantityReserved: 1, quantityAvailable: 13 },
      },
      {
        id: 'sku-008-gld',
        skuCode: 'SGL-TTN-GLD',
        price: 1890000,
        isActive: true,
        attributes: { Frame: 'Vàng Champagne (Champagne Gold)', Lens: 'Nâu Trà' },
        inventory: { quantityOnHand: 6, quantityReserved: 1, quantityAvailable: 5 },
      },
    ],
  },
];

export const MOCK_USER_ADDRESSES: CustomerAddress[] = [
  {
    id: 'addr-001',
    customerId: 'cust-demo-001',
    recipientName: 'Nguyễn Văn An',
    phone: '0987654321',
    line1: 'Tầng 15, Tòa nhà Landmark 81, 720A Điện Biên Phủ',
    line2: 'Khu đô thị Vinhomes Central Park',
    ward: 'Phường 22',
    district: 'Quận Bình Thạnh',
    city: 'Thành phố Hồ Chí Minh',
    isDefault: true,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'addr-002',
    customerId: 'cust-demo-001',
    recipientName: 'Nguyễn Văn An (Văn phòng)',
    phone: '0912345678',
    line1: 'Số 45 Đường Lê Duẩn',
    ward: 'Phường Bến Nghé',
    district: 'Quận 1',
    city: 'Thành phố Hồ Chí Minh',
    isDefault: false,
    createdAt: '2026-03-15T14:30:00Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-2026-001',
    orderNumber: 'ORD-20260920-8841',
    customerId: 'cust-demo-001',
    status: 'COMPLETED',
    subtotalAmount: 1850000,
    shippingFeeAmount: 0,
    discountAmount: 0,
    grandTotalAmount: 1850000,
    currency: 'VND',
    createdAt: '2026-09-15T09:12:00Z',
    shippingAddress: MOCK_USER_ADDRESSES[0],
    items: [
      {
        id: 'item-001',
        skuId: 'sku-005-slv',
        skuCodeSnapshot: 'LMP-SPC-SLV',
        productNameSnapshot: 'Đèn Bàn Công nghệ LED Smart Spectrum Pro',
        productImageSnapshot: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=400&q=80',
        attributeSnapshot: { Finish: 'Nhôm Bạc Xước (Silver)' },
        quantity: 1,
        unitPriceSnapshot: 1850000,
        lineTotal: 1850000,
      },
    ],
    timeline: [
      {
        id: 'tl-1',
        orderId: 'ord-2026-001',
        fromStatus: null,
        toStatus: 'RESERVED',
        actorType: 'CUSTOMER',
        actorId: 'cust-demo-001',
        note: 'Đơn hàng được khởi tạo thành công và giữ chỗ kho hàng',
        occurredAt: '2026-09-15T09:12:00Z',
      },
      {
        id: 'tl-2',
        orderId: 'ord-2026-001',
        fromStatus: 'RESERVED',
        toStatus: 'PAID',
        actorType: 'SYSTEM',
        note: 'Thanh toán trực tuyến thành công qua Cổng thanh toán',
        occurredAt: '2026-09-15T09:14:22Z',
      },
      {
        id: 'tl-3',
        orderId: 'ord-2026-001',
        fromStatus: 'PAID',
        toStatus: 'PACKING',
        actorType: 'BACK_OFFICE',
        note: 'Kho đóng gói sản phẩm và đính kèm mã vận đơn',
        occurredAt: '2026-09-15T11:00:00Z',
      },
      {
        id: 'tl-4',
        orderId: 'ord-2026-001',
        fromStatus: 'PACKING',
        toStatus: 'SHIPPED',
        actorType: 'BACK_OFFICE',
        note: 'Đã bàn giao cho đơn vị vận chuyển GHN (Mã: GHN-VN-99238)',
        occurredAt: '2026-09-15T15:30:00Z',
      },
      {
        id: 'tl-5',
        orderId: 'ord-2026-001',
        fromStatus: 'SHIPPED',
        toStatus: 'COMPLETED',
        actorType: 'SYSTEM',
        note: 'Giao hàng thành công đến tay người nhận',
        occurredAt: '2026-09-17T10:15:00Z',
      },
    ],
  },
  {
    id: 'ord-2026-002',
    orderNumber: 'ORD-20260925-1092',
    customerId: 'cust-demo-001',
    status: 'PAID',
    subtotalAmount: 680000,
    shippingFeeAmount: 30000,
    discountAmount: 0,
    grandTotalAmount: 710000,
    currency: 'VND',
    createdAt: '2026-09-25T14:20:00Z',
    shippingAddress: MOCK_USER_ADDRESSES[0],
    items: [
      {
        id: 'item-002',
        skuId: 'sku-001-blk-m',
        skuCodeSnapshot: 'HD-BLK-M',
        productNameSnapshot: 'Áo Hoodie Minimalist Heavyweight Oversized',
        productImageSnapshot: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80',
        attributeSnapshot: { Color: 'Đen (Obsidian)', Size: 'M' },
        quantity: 1,
        unitPriceSnapshot: 680000,
        lineTotal: 680000,
      },
    ],
    timeline: [
      {
        id: 'tl-21',
        orderId: 'ord-2026-002',
        fromStatus: null,
        toStatus: 'RESERVED',
        actorType: 'CUSTOMER',
        actorId: 'cust-demo-001',
        note: 'Đơn hàng được khởi tạo thành công',
        occurredAt: '2026-09-25T14:20:00Z',
      },
      {
        id: 'tl-22',
        orderId: 'ord-2026-002',
        fromStatus: 'RESERVED',
        toStatus: 'PAID',
        actorType: 'SYSTEM',
        note: 'Xác nhận thanh toán thành công',
        occurredAt: '2026-09-25T14:22:15Z',
      },
    ],
  },
];
